name: API
on:
  push:
    branches: ['master']
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          port: 22
          script: |
            cd ~/sites/cyrus-api
            git pull origin master
            git status
            npm install
            npm build
            pm2 restart dist/index.js