name: API
on:
  push:
    branches: ['master']
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          port: 22
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Test
        run: git pull https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git master
      # - name: Install dependencies
      #   run: npm ci
      # - name: Build 
      #   run: npm run build
      # - name: Restart pm2
      #   run: pm2 restart dist/index.js