name: Docs
on:
  push:
    branches: ['master']
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          port: 22
          script: |
            cd ~/sites/cyrus-api
            rm -r node_modules
            rm package-lock.json
            git pull origin master
            npm install
            npm run docs:build
            pm2 restart ecosystem.config.js